### ISSUE TITLE
about database downloading

### ISSUE THREAD

**Issue by chuangyu-robotics** [vijay4313/proxemo#1]
proxemo is interestingly used in Human-robot interaction. Thank you for you to share your work here.

Could you tell me where I can download a whole database of proxemo?

Thanks in advance!

**Comment by vijay4313** [comment]
Hello Chuang,

I'm happy that ProxEmo interests you!.
Regarding the dataset, the action joints are from the ELMD dataset
mentioned in the readme. But the original dataset was labeled for action
recognition. Our group got it labeled for emotion. I have attached the data
and the labels with this email (features_EMLD.h5
<https://drive.google.com/file/d/1GxUaP2WJ9h20zkHkHQlz7nVpjiDJEFkP/view?usp=sharing>
file
drive link). You can use this database but please cite the original papers
that introduced these datasets in your work. I have given the
original papers below.:


   1. T. Randhavane, U. Bhattacharya, K. Kapsaskis, K. Gray, A. Bera, and
   D. Manocha, “Learning perceived emotion using affective and deep features
   for mental health applications,” in 2019 ISMAR, Oct 2019.
   2.
   https://bitbucket.org/jonathan-schwarz/edinburgh_locomotion_mocap_dataset/src/master/


Let me know if you are able to download all the files. Feel free to let me
know if you have any questions.

Regards,
Venkatraman

**Comment by chuangyu-robotics** [comment]
Hi, Venkatraman,

Yes, I can download it. 

Thank you very much!!! 

So kind of you with so detailed information.

Best wishes,

Chuang
